config/routes.rb
Project1::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects do
    member do
      get :edit_data, :edit_viz, :edit_share
    end
  end
  resources :rel_projects, only: [:create, :destroy]
  resources :vizs, only: [:create, :destroy]
  resources :datasets, only: [:create, :destroy]

  root to: 'main_pages#home'

  match '/signup', to: "users#new"

  match '/signin', to: "sessions#new"

  match '/signout', to: "sessions#destroy", via: :delete

  match '/help', to: "main_pages#help"

  match '/about', to: "main_pages#about"

end

app/views/shared/_dataset_form.html.erb
<div class="viz_form">
    <section>
        <div class="span3">
    		  <h1>Upload your Data</h1>
        </div>
        <div class="span4 pagination-right">
            <%= form_for(@viz) do |f| %>
                <%= f.submit "Upload Dataset", class: "btn btn-large btn" %>
            <% end %>
        </div>
        <div class="span2">
            <%= form_for(@viz) do |f| %>
                <%= f.submit "Use Spreadsheet", class: "btn btn-large btn-primary" %>
            <% end %>
        </div>

    </section>
    <section>

    <%= form_for(@dataset) do |f| %>

        <%= render 'shared/error_messages', object: f.object %>

        <%= render 'shared/spreadsheet_form' %>

    <% end %>

    </section>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_join.html.erb
<%= form_for(current_user.rel_projects.build(project_id: @project.id)) do |f| %>
	<div><%= f.hidden_field :project_id %></div>
	<%= f.submit "Join Project", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_join_button.html.erb
<% if @project.has_user?(current_user) %>
	<%= render 'shared/leave' %>
<% else %>
	<%= render 'shared/join' %>
<% end %>

app/views/shared/_leave.html.erb
<%= form_for(current_user.rel_projects.find_by_project_id(@project),
			 html: { method: :delete }) do |f| %>
	<%= f.submit "Leave Project", class: "btn btn-large" %>
<% end %>

app/views/shared/_project_datasets.html.erb
<% unless @project.datasets.count == 0 %>
	<% @project.datasets.each do |dataset| %>
		<% unless dataset.rows.nil? %>
			<div class="row">
					<div class="span10">
						<h3><%= dataset.name %></h3>
						<span class="timestamp">
							<%= dataset.created_at %>
						</span>
					</div>
					<div class="span10">
						<%= dataset.rows[:a1] %>
						<%= dataset.rows[:a2] %>
						<%= dataset.rows[:a3] %>
						<%= dataset.rows[:a4] %>
						<%= dataset.rows.count %>
						<%= dataset.row_length %>
						<%= dataset.num_rows %>
					</div>
				</div>
		<% end %>
	<% end %>
<% end %>

app/views/shared/_project_details.html.erb
<%= @project.datasets.count %> datasets
<br/><br/>
<% @project.datasets.each do |dataset| %>
	<div>
	<%= dataset.name %>
	</div>
<% end %>

app/views/shared/_project_nav.html.erb
<h1><%= @project.title %></h1>
<% if @project.has_user?(current_user) %>	
	<% if signed_in? %>
	
	<div class="row center" style="background-color: #f0f0f0; margin-top:-20px; margin-bottom: 40px;">

	<% if get_edit_state == 0 %>
		<div class="span3" style="background-color: #000">
			<h3 style="color: #ccc">Upload Data</h3>
		</div>
		<div class="span4">
			<h3><%= link_to "Create Viz",    edit_viz_project_path(@project) %></h3>
		</div>
		<div class="span3">
			<h3><%= link_to "Share!",    edit_share_project_path %></h3>
		</div>

	<% elsif get_edit_state == 1 %>
	
		<div class="span3">
			<h3><%= link_to "Upload Data",    edit_data_project_path %></h3>
		</div>
		<div class="span4" style="background-color: #000">
			<h3 style="color: #ccc">Create Viz</h3>
		</div>
		<div class="span3">
			<h3><%= link_to "Share!",    edit_share_project_path %></h3>
		</div>

	<% else %>

		<div class="span3">
			<h3><%= link_to "Upload Data",    edit_data_project_path %></h3>
		</div>
		<div class="span4">
			<h3><%= link_to "Create Viz",    edit_viz_project_path %></h3>
		</div>
		<div class="span3" style="background-color: #000">
			<h3 style="color: #ccc">Share!</h3>
		</div>

	<% end %>
	</div>

	<% end %>
<% end %>

app/views/shared/_spreadsheet_form.html.erb
<%= form_for(@dataset) do |f| %>
    <section>
        <div class="span6">
            <%= f.text_field :name, placeholder: "Give your Dataset a name" %>
        </div>
    </section>
    <section>
        <div class="span9">
            <div class="spread_cell">
                <%= f.text_field :a1, placeholder: "A1" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a2, placeholder: "A2" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a3, placeholder: "A3" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a4, placeholder: "A4" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a5, placeholder: "A5" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a6, placeholder: "A6" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a7, placeholder: "A7" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a8, placeholder: "A8" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :a9, placeholder: "A9" %>
            </div>
        </div>
    </section>
    <section>
        <div class="span9">
            <div class="spread_cell">
                <%= f.text_field :b1, placeholder: "B1" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b2, placeholder: "B2" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b3, placeholder: "B3" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b4, placeholder: "B4" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b5, placeholder: "B5" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b6, placeholder: "B6" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b7, placeholder: "B7" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b8, placeholder: "B8" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :b9, placeholder: "B9" %>
            </div>
        </div>
    </section>
    <section>
        <div class="span9">
            <div class="spread_cell">
                <%= f.text_field :c1, placeholder: "C1" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c2, placeholder: "C2" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c3, placeholder: "C3" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c4, placeholder: "C4" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c5, placeholder: "C5" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c6, placeholder: "C6" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c7, placeholder: "C7" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c8, placeholder: "C8" %>
            </div>
            <div class="spread_cell">
                <%= f.text_field :c9, placeholder: "C9" %>
            </div>
        </div>
    </section>
    <section class="center">
            <!-- for the currently hard-coded spreadsheet, we
                hard-code the row_length and num_rows. 
                This would obviously have to change for 
                dynamic datasets or datasets from uploaded
                files.  -->
            <%= f.hidden_field :row_length, value:9 %>
            <%= f.hidden_field :num_rows, value:3 %>
            <%= f.submit "Save Dataset", class: "btn btn-large btn-primary" %>
    </section>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>

app/views/shared/_user_projects.html.erb
<% current_user.rel_projects.each do |rel| %>
	<% @project = Project.find_by_id(rel.project_id) %>
	<div class="project_box">
		<h3><%= link_to @project.title, @project %></h3>
	</div>
<% end %>