config/routes.rb
Project1::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects do
    member do
      get :edit_data, :edit_viz, :edit_share
    end
  end
  resources :rel_projects, only: [:create, :destroy]
  resources :vizs, only: [:create, :destroy]
  resources :datasets, only: [:create, :destroy]

  root to: 'main_pages#home'

  match '/signup', to: "users#new"

  match '/signin', to: "sessions#new"

  match '/signout', to: "sessions#destroy", via: :delete

  match '/help', to: "main_pages#help"

  match '/about', to: "main_pages#about"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.google.com/">Project 1</a>
    by Daniel Chang
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "viz.ly", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>

            <!-- Projects Menu -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Projects <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "  + Create New!", "/projects/new" %></li>
                <% current_user.rel_projects.each do |rel| %>
                  <% @project = Project.find_by_id(rel.project_id) %>
                  <li><%= link_to @project.title, @project %></li>
                <% end %>
              </ul>
            </li>

            <!-- Account Menu -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
    	<title><%= full_title(yield(:title)) %></title>
      <%= yield(:head) %>
    	<%= stylesheet_link_tag    "application", media: "all" %>
    	<%= javascript_include_tag "application" %>
    	<%= csrf_meta_tags %>
    	<%= render 'layouts/shim' %>
  	</head>
  	<body>
    	<%= render 'layouts/header' %>
    	<div class="container">
      		<% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %>"><%= value %></div>
      		<% end %>
      		<%= yield %>
      		<%= render 'layouts/footer' %>
      		<%= debug(params) if Rails.env.development? %>
    	</div>
  	</body>
</html>